In [6]:
import pandas as pd

# Load the Excel file
file_path = '/Users/xiaofanjiao/Desktop/vegan.xlsx'

In [15]:
# Load the data from 'vegan' sheet
vegan_data = pd.read_excel(file_path, sheet_name='Vegan', header=None)
vegan_data.head(20)  # Display the first 20 rows to see the data structure.

                                                    0
0                                        Name: PLANTA
1   Address: 1221 Bay St., Toronto, ON M5R 3P5, Ca...
2                                         Rating: 4.4
3                        Phone Number: (647) 812-1221
4   Website: https://www.plantarestaurants.com/loc...
5                                              ------
6                                    Name: Eat Nabati
7   Address: 160 Baldwin St, Toronto, ON M5T 3K7, ...
8                                         Rating: 4.7
9                        Phone Number: (289) 277-0008
10                    Website: https://eatnabati.com/
11                                             ------
12                         Name: Rosalinda Restaurant
13  Address: 133 Richmond St W, Toronto, ON M5H 2L...
14                                        Rating: 4.3
15                       Phone Number: (416) 907-0650
16           Website: http://rosalindarestaurant.com/
17                                             ------
18                    Name: Fresh Kitchen + Juice Bar
19  Address: 47 Front St E, Toronto, ON M5E 1B3, C...

In [17]:
import pandas as pd

def parse_vegan_data(data):
    # Initialize an empty list to hold the parsed data
    parsed_data = []
    
    # Temporary dictionary to store each entry
    entry = {}
    
    # Iterate over the rows in the dataframe
    for index, row in data.iterrows():
        # Convert the cell content to string and check for '------'
        if isinstance(row[0], str) and '------' in row[0]:
            # If the entry dictionary is not empty, append it to the list
            if entry:
                parsed_data.append(entry)
                entry = {}
        else:
            # Check if row is not empty and contains ': '
            if isinstance(row[0], str) and ': ' in row[0]:
                key, value = row[0].split(': ', 1)
                entry[key] = value
            
    # Append the last entry if it's not empty
    if entry:
        parsed_data.append(entry)
    
    # Create a dataframe from the parsed data
    structured_data = pd.DataFrame(parsed_data)
    
    # Return the structured dataframe
    return structured_data

# Assuming 'vegan_data' is your initial DataFrame
structured_vegan_data = parse_vegan_data(vegan_data)

# Display the structured dataframe
structured_vegan_data.head()

,Name,Address,Rating,Phone Number,Website
0,PLANTA,"1221 Bay St., Toronto, ON M5R 3P5, Canada",4.4,(647) 812-1221,https://www.plantarestaurants.com/location/pla...
1,Eat Nabati,"160 Baldwin St, Toronto, ON M5T 3K7, Canada",4.7,(289) 277-0008,https://eatnabati.com/
2,Rosalinda Restaurant,"133 Richmond St W, Toronto, ON M5H 2L3, Canada",4.3,(416) 907-0650,http://rosalindarestaurant.com/
3,Fresh Kitchen + Juice Bar,"47 Front St E, Toronto, ON M5E 1B3, Canada",4.3,(647) 693-7556,https://www.freshkitchens.ca/en/locations/on/t...
4,Kupfert & Kim,"140 Spadina Ave., Toronto, ON M5V 2L4, Canada",4.3,(416) 504-2206,http://www.kupfertandkim.com/

In [18]:
# Save the structured data to a new Excel file
output_file_path = '/Users/xiaofanjiao/Desktop/vegan_cleaned.xlsx'
structured_vegan_data.to_excel(output_file_path, index=False)